FROM golang:latest

WORKDIR /backend

COPY ./backend .

RUN go mod download

RUN go get github.com/githubnemo/CompileDaemon

EXPOSE 8080
WORKDIR "./backend"

ENTRYPOINT CompileDaemon --build="go build ./cmd/api/main.go" --command=./main